openapi: "3.0.0"
info:
  version: 4.0.1
  title: Common Schemas
  description: Common Schemas, based on TIP 4.0.0 documentation
  termsOfService: http://placeholderdomain.io/terms/ # TODO
  contact:
    name: TIP Forum # TODO
    email: tip-mailing-list@tbd.com # TODO
    url: http://placeholderdomain.io # TODO
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT # TODO 

paths: {} # no paths

components:
  examples:
    RFPResponse:
      value:
        transactionId: "A12312BASDF"
        transactionDate: "2016-03-22T21:03:41"
      summary: Sample Response Data