openapi: 3.0.0
info:
  version: 5.0.0
  title: Inventory Avails Schemas
  description: Inventory Avails Schemas
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    InventoryAvailsBuyerObject:
      description: Allows the Buyer as campaign planning to initiate an inventory Request to the Seller
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        dateSubmitted:
          description: Buyer Submit Date for Inventory Request
          type: string
          format: date
        dueDate:
          description: Due Date for seller to respond with Inventory Information
          type: string
          format: date
        mediaOutlets:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
          minItems: 1
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        contacts:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        timePeriods:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/TimePeriod'
          minItems: 1
        guidelines:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Guideline'
        political:
          description: Indicates if the request is for political pricing
          type: boolean
        inventoryTypes:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/InventoryType'
        maxRate:
          description: Max rate spend across all inventory types
          type: number
          format: float
          minimum: 0
          exclusiveMinimum: true
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the
            TIP flow
          type: string
        audienceSegments:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegment'
          minItems: 1
        pricingMetricOptions:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/PricingMetricOption'
      required:
        - transactionHeader
        - dateSubmitted
        - mediaOutlets
        - timePeriods
        - political
        - audienceSegments
    InventoryAvailsSellerObject:
      description: >-
        Allows the Seller to post to the buyer their catalog of selling products, pricing and audience
        information
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        dateSubmitted:
          description: Submission date for the inventory
          type: string
          format: date
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        contacts:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        rateCard:
          $ref: 'commonSchemas.yaml#/components/schemas/RateCard'
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        political:
          description: Indicates that pricing being supplied are for political
          type: boolean
        mediaOutlets:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
          minItems: 1
        audienceSegments:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegmentDetail'
        availWindow:
          $ref: 'commonSchemas.yaml#/components/schemas/DateWindow'
        salesElements:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/SalesElement'
          minItems: 1
      required:
        - transactionHeader
        - dateSubmitted
        - political
        - mediaOutlets
        - availWindow
        - salesElements
