openapi: "3.0.0"
components:
 securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
info:
  version: 5.0.0
  title: Inventory Avails
  description: Inventory Endpoints
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io/v5.x.x

paths:
  /buyer/inventoryAvails:
    post:
      tags:
        - Buyer
      summary: Allows the Buyer as part of campaign planning to initiate an Inventory Request to Seller
      description: >-
        This endpoint is hosted at the seller end, Allows the Buyer as part of campaign planning
        to initiate an Inventory Request to Seller. The payload of the request can either be:<br/>
        NOTE#1: For New Request --> transactionId.transactionType=New<br/>
        NOTE#2: for Changing a previously submitted request --> <br/>
        <li>transactionId.transactionType=Change<br/>
        <li>originalTransactionId object must be provided
      operationId: BuyerInventoryAvails
      requestBody:
        description: Send the request for the inventory avails required
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/BuyerInventoryAvails'
      responses:
        '200': #OK - in case request can be fullfiled in realtime
          $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/SellerInventoryAvails'
        '202': #Accepted
          $ref: 'schemas/commonResponses.yaml#/components/responses/Accepted'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
  # /buyer/inventoryAvails/cancel:
  #   post:
  #     tags:
  #       - Buyer
  #     summary: Cancel inventory Avails request
  #     description: >-
  #       This endpoint will be hosted at the seller side.
  #       This endpoint allows the buyer to request from the seller to cancel and ignore
  #       a previously communicated inventoryAvails request. As Follows:<br/>
  #       NOTE#1: originalTransactionId values needs to indicate which request is to be cancelled.<br/>
  #       NOTE#2: transactionId.transactionType = Cancel<br/>
  #       NOTE#3: originalTransactionId.transactionId must refer to the transaction in question to be cancelled
  #     operationId: BuyerInventoryAvailsCancel
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: 'schemas/commonSchemas.yaml#/components/schemas/TransactionHeader'
  #     responses:
  #       '200': #OK
  #         $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
  #       '400': #Bad Request
  #         $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
  #       '401': #Unauthorized
  #         $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
  #       '403': #Forbidden
  #         $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
  #       '404': #Not Found
  #         $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
  #       '405': #Not Allowed
  #         $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
  #       default: #unexpected
  #         $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
  /seller/inventoryAvails:
    post:
      tags:
        - Seller
      summary: Allows the Seller to post to the buyer their catalog of selling products, pricing and audience information
      description: >
        This endpoint will be hosted at the buyer side,
        Allows the Seller to send inventory criteria such as Stations, Selling Elements, Inventory Types, Pricing, Audience Estimates
        either solicited or unsolicited
      operationId: SellerInventoryAvails
      requestBody:
        description: Seller POSTs the the Inventory Avails information to the buyer's system
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/SellerInventoryAvails'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
  # /seller/inventoryAvails/cancel:
  #   post:
  #     tags:
  #       - Seller
  #     summary: Cancel inventory Avails Request
  #     description: >-
  #       This endpoint will be hosted at the buyer side.
  #       This endpoint allows the buyer to request from the seller to cancel and ignore
  #       a previously communicated inventoryAvails request. As Follows:<br/>
  #       NOTE#1:originalTransactionId values needs to indicate which request is to be cancelled.<br/>
  #       NOTE#2: transactionId.transactionType = Cancel<br/>
  #       NOTE#3: originalTransactionId.transactionId must refer to the transaction in question to be cancelled

  #     operationId: SellerInventoryAvailsCancel
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: 'schemas/commonSchemas.yaml#/components/schemas/TransactionHeader'
  #     responses:
  #       '200': #OK
  #         $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
  #       '400': #Bad Request
  #         $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
  #       '401': #Unauthorized
  #         $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
  #       '403': #Forbidden
  #         $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
  #       '404': #Not Found
  #         $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
  #       '405': #Not Allowed
  #         $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
  #       default: #unexpected
  #         $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'

