openapi: "3.0.0"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

info:
  version: 5.0.0
  title: Invoice
  description: Allows the seller to send to the buyer both new and revised invoice information
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://placeholderdomain.io

paths:
  /seller/invoice:
    post:
      tags:
        - Seller
      summary: Seller Invoice POST
      description: >-
        Allows the seller to send to the buyer new invoice information (No Request from buyer is
        Required)
      operationId: invoicePostSeller
      requestBody:
        description: Invoice body included in request
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/invoiceSchemas.yaml#/components/schemas/InvoiceObject'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/TransactionHeader'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
  /seller/invoice/cancel:
    post:
      tags:
        - Seller
      summary: Seller Invoice Cancel
      description: >-
        This endpoint will be hosted at the buyer side.
        This endpoint allows the seller to request from the buyer to cancel and ignore
        a previously communicated Invoice request. As Follows:<br/>
        NOTE#1:originalTransactionNum values needs to indicate which request is to be cancelled.<br/>
        NOTE#2: transactionNum.transactionType = Cancel<br/>
        NOTE#3: originalTransactionNum.transactionNum must refer to the transaction in question to be cancelled
      operationId: invoiceSellerCancel
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commonSchemas.yaml#/components/schemas/TransactionHeader'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: unexpected error, return the appropriate and corresponding HTTP status code matching the error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

