openapi: "3.0.0"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

info:
  version: 5.x.x
  title: Invoice
  description: Allows the seller to send to the buyer both new and revised invoice information
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://placeholderdomain./v5.x.x

paths:
  /seller/invoices:
    post:
      tags:
        - Seller
      summary: Seller submits an invoice to buyer
      description: >-
        Allows the seller to send to the buyer new invoice information (No Request from buyer is
        Required)
      operationId: SellerInvoice
      requestBody:
        description: Invoice body included in request
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: 'schemas/invoiceSchemas.yaml#/components/schemas/SellerInvoices'
                - $ref: 'schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
              # discriminator:
              #   propertyName: transactionHeader.transactionId.transactionType
              #   mapping:
              #     New: './schemas/invoiceSchemas.yaml#/components/schemas/SellerInvoice'
              #     Cancel: './schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
            examples:
              New:
                value:
                  $ref: 'examples/WIP-Examples/SellerInvoiceNew.json'
              Cancel:
                value:
                  $ref: 'examples/WIP-Examples/GenericCancel.json'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'

