openapi: "3.0.0"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

info:
  version: 5.x.x
  title: Makegoods
  description: Makegoods
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Forum
    email: tip-mailing-list@tbd.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io/tip/v5.x.x

paths:
  /seller/makegoodGuidlines:
    post:
      tags:
        - Seller
      summary: Seller submits a request for buyer's makegood guidelines
      description: Seller submits a request for buyer's makegood guidelines
      operationId: SellerMakegoodGuidelines
      requestBody:
        description: GetMakegoodGuidelines
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/SellerMakegoodGuidelines'
      responses:
        '202': #Accepted
          $ref: 'schemas/commonResponses.yaml#/components/responses/Accepted'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'

  /buyer/makegoodGuidelines:
    post:
      tags: 
        - Buyer
      summary: Buyer responds back to seller with list of makegood guidelines
      description: Buyer responds back to seller with list of makegood guidelines 
      operationId: BuyermakegoodGuidelines
      requestBody:
        description: Makegoods
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/BuyerMakegoodGuidelines'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'

  /seller/makegood/Offer:
    post:
      tags:
        - Seller
      summary: Receive Makegood Offer
      description: >
        Seller sends to Buyer one too many offer requests to support the following:
        Makegood to resolve unresolved Preemptions
        "ADU" to resolve make-up for audience shortfall 
      operationId: SellerMakegoodOffer
      requestBody:
        description: MakegoodOffer
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/SellerMakegoodOffer'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'

  /buyer/makegood/confirm:
    post:
      tags:
        - Buyer
      summary: Makegood Confirm
      description: >
        Allows the  buyer to respond to an makegood offer(s) with an acceptance confirmation; 
        this will accept all makegood offers in the request
      operationId: BuyerMakegoodConfirm
      requestBody:
        description: MakegoodOfferConfirm
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/BuyerMakeGoodConfirm'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'

  /buyer/makegood/reject:
    post:
      tags:
        - Buyer
      summary: Reject a Makegood offer
      description: >
        Allows the buyer to reject makegood offer(s)request; 
        buyer will request everything in the request and include rejection comments
      operationId: BuyerMakegoodReject
      requestBody:
        description: Buyer Reject makegood offer
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/BuyerMakegoodReject'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'

  /seller/makegood/recall:
    post:
      tags: 
        - Seller
      summary: Seller Makegood Recall
      description: >
        Allows the seller to recall a makegood offer request;
        buyer must respond with acceptance or failure.
        Note: buyer's system defines rules of acceptance or failure
      operationId: SellerMakegoodRecall
      requestBody:
        description: Seller recalls makegood Offer
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/SellermakegoodRecall'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
