openapi: "3.0.0"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

info:
  version: 5.x.x
  title: Makegoods
  description: Makegoods
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Forum
    email: tip-mailing-list@tbd.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io/tip/v5.x.x

paths:
  /seller/makegoodGuidlines:
    post:
      tags:
        - Seller
      summary: Seller asks for Makegood Guidelines
      description: Seller submits a request for buyer's makegood guidelines
      requestBody:
        description: GetMakegoodGuidelines
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/SellerMakegoodGuidelines'
      responses:
        '202': #Accepted
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        '400': #Bad Request
          description: payload is ill formed or cantains data that is invalid 
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        '401':
          description: Unauthorized, invalid credentials or expired access token
          headers:
            WWW-Authenticate:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        '403':
          description: Forbidden, additional previliges are needed
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /buyer/makegoodGuidelines:
    post:
      tags: 
        - Buyer
      summary: Buyer provides makegood guidlines to seller
      description: Buyer submits a list of the makegood guidelines to seller prior to order confirmation 
      requestBody:
        description: Makegoods
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/BuyerMakegoodGuidelines'
      responses:
        '200': # OK
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        '400': #Bad Request
          description: payload is ill formed or cantains data that is invalid 
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        '401':
          description: Unauthorized, invalid credentials or expired access token
          headers:
            WWW-Authenticate:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        '403':
          description: Forbidden, additional previliges are needed
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /seller/makegood/Offer:
    post:
      tags:
        - Seller
      summary: Receive Makegood Offer
      description: >
        Seller sends to Buyer one too many offer requests to support the following:
        Makegood to resolve unresolved Preemptions
        "ADU" to resolve make-up for audience shortfall 
        "Recap" to support projected audience shortfall 
      requestBody:
        description: MakegoodOffer
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/SellerMakegoodOffer'
      responses:
        '202': # Accepted
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        '400': #Bad Request
          description: payload is ill formed or cantains data that is invalid 
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        '401': # Unauthorized
          description: Unauthorized, invalid credentials or expired access token
          headers:
            WWW-Authenticate:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        '403': #Forbidden
          description: Forbidden, additional previliges are needed
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        default: # Any unexpected error
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /buyer/makegood/confirm:
    post:
      tags:
        - Buyer
      summary: Makegood Confirm
      description: >
        Allows the  buyer to respond to an makegood offer(s) with an acceptance confirmation; 
        this will accept all makegood offers in the request
      requestBody:
        description: MakegoodOfferConfirm
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/BuyerMakeGoodConfirm'
      responses:
        '200': # OK
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        '400': #Bad Request
          description: payload is ill formed or cantains data that is invalid 
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        '401': # Unauthorized
          description: Unauthorized, invalid credentials or expired access token
          headers:
            WWW-Authenticate:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        '403': #Forbidden
          description: Forbidden, additional previliges are needed
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        default: # Any unexpected error
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /buyer/makegood/reject:
    post:
      tags:
        - Buyer
      summary: Makegood Reject
      description: >
        Allows the buyer to reject makegood offer(s)request; 
        buyer will request everything in the request and include rejection comments
      requestBody:
        description: cancelMakegood
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/BuyerMakegoodReject'
      responses:
        '200': # OK
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        '400': #Bad Request
          description: payload is ill formed or cantains data that is invalid 
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        '401': # Unauthorized
          description: Unauthorized, invalid credentials or expired access token
          headers:
            WWW-Authenticate:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        '403': #Forbidden
          description: Forbidden, additional previliges are needed
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        default: # Any unexpected error
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /seller/makegood/recall:
    post:
      tags: 
        - Seller
      summary: Seller Makegood Recall
      description: >
        Allows the seller to recall a makegood offer request ; 
        buyer must respond back with acceptance or failure of the recall request.
          Note: buyer's system defines the rules for acceptance or failure of request  				
      requestBody:
        description: cancelMakegood
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/SellermakegoodRecall'
      responses:
        '200': # OK
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        '400': #Bad Request
          description: payload is ill formed or cantains data that is invalid 
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        '401': # Unauthorized
          description: Unauthorized, invalid credentials or expired access token
          headers:
            WWW-Authenticate:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        '403': #Forbidden
          description: Forbidden, additional previliges are needed
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
        default: # Any unexpected error
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'