openapi: "3.0.0"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

info:
  version: 5.0.0
  title: Orders
  description: >-
    Allows the seller to respond back to the buyer with the detailed proposal for a given RFP
    or revised proposal; Multiple versions of a proposal can be under negotiation for
    the same campaign, but only one version may be executed; buyer must submit a "Proposal Change Request" for the last proposal version submission; seller must respond back with a Proposal Response that contains a new version number when submitting new versions.  New Proposals may be submitted without a RFP Response
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Forum
    email: tip-mailing-list@tbd.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

paths:
  /buyer/order:
    post:
      tags:
        - Buyer
      summary: Create an Order
      description: >-
        The endpoint resides on the seller side. <br/>
        the endpoint allows the buyer to creates an order in the Seller system.
      operationId: createOrder
      requestBody:
        description: createOrder
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/ordersSchemas.yaml#/components/schemas/BuyerOrderRequestObject'
      responses:
        '202':
          description: >-
            Your request was received.<br/>
            The request has been accepted for processing, but the processing has not been completed.<br/>
            The request might or might not eventually be acted upon, as it might be disallowed when processing actually takes place.
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: Error.
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
  /buyer/order/cancel:
    post:
      tags:
        - Buyer
      description: >-
        The endpoint resides on the seller side. <br/>
        the endpoint allows the buyer to creates an order in the Seller system.
      operationId: cancelOrder
      requestBody:
        description: cancelOrder
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/ordersSchemas.yaml#/components/schemas/OrderRecallObject'
      responses:
        '200':
          description: >-
            Cancel request received.
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: Error.
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
  /seller/order/confirmation:
    post:
      tags:
        - Seller
      summary: Confirmation of acceptance of previously submitted order
      description: >-
        The endpoint resides on the buyer side to allow the seller to send a confirmation<br/>
        regarding the successful processing of previously submitted order.<br/>
        originalTransactionNum is required for Audit Trail.
      operationId: orderConfirmation
      requestBody:
        description: Order Confirmation
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/ordersSchemas.yaml#/components/schemas/OrderConfirmationResponseObject'
      responses:
        '200':
          description: confirmation Accepted
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: Error.
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
  /seller/order/reject:
    post:
      tags:
        - Seller
      summary: Reject of previously submitted order
      description: >-
        The endpoint resides on the buyer side to allow the seller to send a reject (all or None)<br/>
        regarding the rejection  of previously submitted order.<br/>
        originalTransactionNum is required for Audit Trail.
      operationId: orderReject
      requestBody:
        description: Order Rejection
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/ordersSchemas.yaml#/components/schemas/OrderRejectResponseObject'
      responses:
        '200':
          description: Rejection Accepted
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: Error.
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
