openapi: "3.0.0"

components:
 securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

info:
  version: 5.1.0
  title: Proposal
  description: |
    * Allows the seller to respond back to the buyer with the detailed proposal for a given RFP or revised proposal;
    Multiple versions of a proposal can be under negotiation for the same campaign, but only one version may be executed; buyer must submit a
    "Proposal Change Request" for the last proposal version submission; seller must respond back with a Proposal Response that contains a new
    version number when submitting new versions.  New Proposals may be submitted without a RFP Response
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

paths:
  /seller/proposals:
    post:
      tags:
        - Seller
      summary: Create or Change a proposal in the buyers system
      description: >-
        Allows the seller to respond back to the buyer with the detailed proposal 
        for a given RFP or revised proposal; Multiple versions of a proposal can be under
         negotiation for the same campaign, but only one version may be executed; 
         buyer must submit a "Proposal Change Request" for the last proposal version submission; 
         seller must respond back with a Proposal Response that contains a new version number 
         when submitting new versions.  New Proposals may be submitted without a RFP Response
      operationId: SellerProposals
      requestBody:
        description: Create, Change, Cancel, or Recall a proposal in the buyers system
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/proposalSchemas.yaml#/components/schemas/SellerProposals'
            examples:
              New:
                value:
                  $ref: 'examples/V5.0.0/SellerProposalNew.json'
              Change:
                value: 
                  $ref: 'examples/WIP-Examples/SellerProposalChange.json'
              Cancel:
                  value:
                    $ref: 'examples/WIP-Examples/GenericCancel.json'
              Recall:
                  value:
                    $ref: 'examples/WIP-Examples/GenericRecall.json'
      responses:
        '202': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Accepted'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
  /buyer/proposals:
    post:
      tags:
        - Buyer
      summary: Buyer change a proposal in the seller's system
      description: >-
        Allows the buyer to respond back to the seller with the proposed changeds for a given proposal; 
        Multiple versions of a proposal can be under negotiation for the same campaign, 
        but only one version may be executed; buyer must submit a 'Proposal Change' for the last proposal version submitted; 
        seller must respond back with a Proposal that contains a new version number when submitting the change          
        NOTE#1:originalTransactionId values needs to indicate which request is to be cancelled.<br/>
        NOTE#2: transactionId.transactionType = Change<br/>
        NOTE#3: originalTransactionId.transactionId must refer to the proposal in question
      operationId: BuyerProposals
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/proposalSchemas.yaml#/components/schemas/SellerProposals'
            examples:
              Change:
                value: 
                  $ref: 'examples/WIP-Examples/SellerProposalChange.json'
              Recall:
                  value:
                    $ref: 'examples/WIP-Examples/GenericRecall.json'
      responses:
        '202': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Accepted'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
