openapi: "3.0.0"

info:
  version: 5.0.0
  title: RFP
  description: Allows the buyer to submit a Request for Proposal (RFP) to the seller with overall media budget, goal and makegood terms and optionally include specific detailed inventory requests
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

components:
 securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /buyer/rfps:
    post:
      tags:
        - Buyer
      summary: Allows the buyer to submit a Request for Proposal (RFP) to the seller with media budget, goals and overall terms
      description: >-
        This endpoint resides on the seller side. the purpose of the endpoint is to allow the buyer to:
        <ol>
        <li>To create New RFP is the seller system. transactionHeader.transactionId.transactionType = New
        <li>To Cancel a previously sent RFP.
        <ol>
        <li>transactionHeader.transactionId.transactionType=Change
        <li>transactionHeader.originalTransactionId.transactionId must indicate the original transactionId</ol></ol>
      operationId: BuyerRFPS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: Allows the buyer to submit a new or cancel a RFP in the seller system
              oneOf:
                - $ref: 'schemas/rfpsSchemas.yaml#/components/schemas/BuyerRfp'
                - $ref: 'schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
              # discriminator:
              #   propertyName: transactionHeader.transactionId.transactionType
              #   mapping:
              #     New: 'schemas/rfpsSchemas.yaml#/components/schemas/BuyerRfp'
              #     Cancel: 'commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
            examples:
              New:
                value:
                  $ref: 'examples/WIP-Examples/BuyerRfpsNew.json'
              Cancel:
                value:
                  $ref: 'examples/WIP-Examples/GenericCancel.json'
      responses:
        '202': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Accepted'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
