openapi: "3.0.0"

info:
  version: 5.0.0
  title: RFP
  description: Allows the buyer to submit a Request for Proposal (RFP) to the seller with overall media budget, goal and makegood terms and optionally include specific detailed inventory requests
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

components:
 securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /buyer/rfp:
    post:
      tags:
        - Buyer
      summary: Allows the buyer to submit a Request for Proposal (RFP) to the seller with media budget, goals and overall terms
      description: >-
        This endpoint resides on the seller side. the purpose of the endpoint is to allow the buyer to:
        A: create New RFP is the seller system. transactionHeader.transactionId.transactionType = New
        B: request changes to be made to a previously communicated RFP.
          in order to correctly handel the change request the following conditions must be satisfied:
          B.1: transactionHeader.transactionId.transactionType=Changed
          B.2: transactionHeader.originalTransactionId.transactionId must indicate the original transactionId
      operationId: NewChangeRFP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/rfpsSchemas.yaml#/components/schemas/BuyerRfp'
      responses:
        '202': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Accepted'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'

  /buyer/rfp/cancel:
    post:
      tags:
        - Buyer
      summary: Cancel a previously submitted RFP in the seller's system.
      description: >-
        Buyer can send this request to cancel a previous request.
        originalTransactionId values needs to indicate which request is to be cancelled.<br/>
        NOTE#1: transactionId.transactionType = Cancel<br/>
        NOTE#2: originalTransactionId.transactionId must refer to the transaction in question to be cancelled
      operationId: CancelRFP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commonSchemas.yaml#/components/schemas/TransactionHeader'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
