openapi: "3.0.0"

info:
  version: 5.0.0
  title: RFP
  description: Allows the buyer to submit a Request for Proposal (RFP) to the seller with overall media budget, goal and makegood terms and optionally include specific detailed inventory requests
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

components:
 securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /buyer/rfp:
    post:
      tags:
        - Buyer
      summary: Create or Change a previously requested an RFP in the seller's system.
      description: >-
        This endpoint resides on the seller side. the purpose of the endpoint is to allow the buyer to:
        A: create New RFP is the seller system. transactionHeader.transactionNum.transactionType = New
        B: request changes to be made to a previously communicated RFP.
          in order to correctly handele the change request the following conditions must be satisfied:
          B.1: transactionHeader.transactionNum.transactionType=Changed
          B.2: transactionHeader.originalTransactionNum.transactionNum must indicate the original transactionNum
      operationId: NewChangeRFP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/rfpsSchemas.yaml#/components/schemas/RFPRequestObject'
      responses:
        '200':
          description: request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /buyer/rfp/cancel:
    post:
      tags:
        - Buyer
      summary: Cancel a previously submitted RFP in the seller's system.
      description: >-
        Buyer can send this request to cancel a previous request.
        originalTransactionNum values needs to indicate which request is to be cancelled.<br/>
        NOTE#1: transactionNum.transactionType = Cancel<br/>
        NOTE#2: originalTransactionNum.transactionNum must refer to the transaction in question to be cancelled
      operationId: CancelRFP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commonSchemas.yaml#/components/schemas/TransactionHeader'
      responses:
        '200':
          description: request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
